package com.utilitybilling.controller;

import com.utilitybilling.dto.response.NotificationLogResponse;
import com.utilitybilling.entity.NotificationLog;
import com.utilitybilling.repository.NotificationLogRepository;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * Additional utility endpoint for viewing notification logs.
 * Useful for testing and verifying that DB triggers and email service are working correctly.
 */
@RestController
@RequestMapping("/api/notifications")
@PreAuthorize("hasAnyRole('ADMIN','FINANCE')")
@SecurityRequirement(name = "bearerAuth")
@Tag(name = "Notification Logs", description = "View system-generated notification logs for audit and testing")
public class NotificationController {

    private final NotificationLogRepository notificationLogRepository;

    public NotificationController(NotificationLogRepository notificationLogRepository) {
        this.notificationLogRepository = notificationLogRepository;
    }

    @Operation(summary = "List all notifications", description = "Returns all notification logs generated by DB triggers and Java service layer.")
    @ApiResponse(responseCode = "200", description = "List of notifications returned",
                 content = @Content(schema = @Schema(implementation = NotificationLogResponse.class)))
    @GetMapping
    public ResponseEntity<List<NotificationLogResponse>> listAll() {
        List<NotificationLog> logs = notificationLogRepository.findAll();
        List<NotificationLogResponse> responses = logs.stream()
                .map(n -> new NotificationLogResponse(
                        n.getId(),
                        n.getCustomer().getId(),
                        n.getCustomer().getFullNames(),
                        n.getMessage(),
                        n.getNotificationType().name(),
                        n.getCreatedAt(),
                        n.isSent()
                ))
                .collect(Collectors.toList());
        return ResponseEntity.ok(responses);
    }

    @Operation(summary = "List notifications by customer", description = "Returns notification logs for a specific customer ID.")
    @ApiResponse(responseCode = "200", description = "List of notifications returned")
    @GetMapping("/customer/{customerId}")
    public ResponseEntity<List<NotificationLogResponse>> listByCustomer(@PathVariable UUID customerId) {
        List<NotificationLog> logs = notificationLogRepository.findByCustomerId(customerId);
        List<NotificationLogResponse> responses = logs.stream()
                .map(n -> new NotificationLogResponse(
                        n.getId(),
                        n.getCustomer().getId(),
                        n.getCustomer().getFullNames(),
                        n.getMessage(),
                        n.getNotificationType().name(),
                        n.getCreatedAt(),
                        n.isSent()
                ))
                .collect(Collectors.toList());
        return ResponseEntity.ok(responses);
    }
}
